/*
 * Copyright (c) 2026 Jóvio Luiz Giacomolli
 * Licensed under the PolyForm Noncommercial License 1.0.0
 * https://polyformproject.org/licenses/noncommercial/1.0.0
 */

package com.polysecure.adapter.jdbc;

import com.polysecure.adapter.StoreCapabilities;
import com.polysecure.catalog.StoreConfig;
import com.polysecure.model.ColumnDefinition;

import java.util.List;
import java.util.stream.Collectors;

public class FirebirdAdapter extends JdbcStoreAdapter {

    public FirebirdAdapter(StoreConfig config) {
        super(config.name(),
            "jdbc:firebirdsql://" + config.host() + ":" + config.port() + "/" + config.database(),
            config.username(), config.password());
    }

    // Firebird has no CREATE TABLE IF NOT EXISTS — tolerate "already exists" (isc code -607)
    @Override
    public void createTable(String table, List<ColumnDefinition> columns) {
        String cols = columns.stream()
            .map(c -> c.name() + " " + toSqlType(c.type()) + (c.primaryKey() ? " PRIMARY KEY" : ""))
            .collect(Collectors.joining(", "));
        try {
            jdbc.execute("CREATE TABLE " + table + " (" + cols + ")");
        } catch (Exception e) {
            if (!e.getMessage().contains("already exists")) throw e;
        }
    }

    @Override
    public void dropTable(String table) {
        try {
            jdbc.execute("DROP TABLE " + table);
        } catch (Exception e) {
            if (!e.getMessage().toLowerCase().contains("unsuccessful metadata update")
                && !e.getMessage().toLowerCase().contains("does not exist")) throw e;
        }
    }

    @Override
    public long estimateCardinality(String table) {
        try {
            Long c = jdbc.queryForObject("SELECT COUNT(*) FROM " + table, Long.class);
            return c != null ? c : 0L;
        } catch (Exception e) {
            return Long.MAX_VALUE;
        }
    }

    @Override
    public List<ColumnDefinition> getSchema(String table) {
        try {
            return jdbc.query(
                "SELECT TRIM(rf.RDB$FIELD_NAME) AS COLUMN_NAME, f.RDB$FIELD_TYPE AS DATA_TYPE " +
                "FROM RDB$RELATION_FIELDS rf JOIN RDB$FIELDS f ON rf.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME " +
                "WHERE rf.RDB$RELATION_NAME = UPPER(?) ORDER BY rf.RDB$FIELD_POSITION",
                (rs, i) -> new ColumnDefinition(rs.getString("COLUMN_NAME"), rs.getString("DATA_TYPE"), storeName, false),
                table);
        } catch (Exception e) {
            return List.of();
        }
    }

    @Override
    public StoreCapabilities getCapabilities() { return StoreCapabilities.full(); }

    @Override
    protected String pingQuery() { return "SELECT 1 FROM RDB$DATABASE"; }

    @Override
    protected String toSqlType(String type) {
        return switch (type.toUpperCase()) {
            case "INT", "INTEGER"              -> "INTEGER GENERATED BY DEFAULT AS IDENTITY";
            case "TEXT", "STRING", "VARCHAR"   -> "VARCHAR(8191)";
            case "BOOLEAN", "BOOL"             -> "BOOLEAN";
            case "FLOAT", "DOUBLE"             -> "DOUBLE PRECISION";
            case "DOCUMENT"                    -> "BLOB SUB_TYPE TEXT";
            default                            -> "VARCHAR(8191)";
        };
    }
}
